name: Run tests & upload coverage to codecov on PR

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-image: [ '1.20.1-bullseye' ]
    steps:
      - uses: actions/checkout@v3
      - name: Run coverage
        run: docker run --rm -v ${{ github.workspace }}:/src -w /src golang:${{ matrix.go-image }} make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
        continue-on-error: true